export const privacyPolicyIntro: string[] = [
  "This Privacy Policy (“Policy”) is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines) Rules, 2011. The Policy is an “Electronic Record” as contemplated under section 2(t) of the information technology Act, 2000 and the rules and is part and parcel of Terms and Conditions. This Policy being an electronic record is generated by a computer system and does not require any physical or digital signature.",
  " B2BSurge Mobile Application (“The Application”) is operated by Techriigour IT Solutions Private Limited, a company incorporated under the laws of India (“Techriigour”) having its registered office at Lotus Resi. S No 15/12, Sangam Press Road, Kothrud, Pune, Maharashtra, India, 411038. ",

  "Users are requested to read and understand the Policy very carefully before using or accessing the application. Through this Policy, Techriigour intends to convey the manner in which the user’s information is collated and used by Techriigour while providing the services of The Application. This Policy is binding on every user of The Application and users who do not agree with the terms of this Policy should not use or access The Application.",

  "Techriigour reserves its right to change, edit, alter, amend, modify, review, revise or substitute this Policy with or without notice. By using the application, the users endorse they have carefully read, understood and agree to be bound by this Policy and the users expressly and voluntarily accept this Policy including any change, modification or substitution made to the Policy from time to time. Techriigour reserves its right to refuse services to any user who does not accept or violates the terms of this Policy",
];

interface PermissionInterface {
  title: string;
  Desc: string;
}

export const permissionSection: PermissionInterface[] = [
  {
    title: "Location",
    Desc: "Techriigour uses this information to provide accurate and improved accuracy for the users in order to make their application experience hassle free and seamless. This can also be used for Fraud Prevention, Security as well as specific compliance requirements as mentioned in further sections",
  },
  {
    title: "Phone state and device Id",
    Desc: "To identify cellular network information and device model/type/operating system version for optimizing performance on low bandwidth network.",
  },
  {
    title: "Camera/Gallery",
    Desc: "The Camera/Gallery Access of the mobile device is only used while within the application to upload profile image, product and services, promotional banners",
  },
  {
    title: "Email Id",
    Desc: "The Email ID of the user is used as an identification for the user of the application to login and access the application. ",
  },
  {
    title: "Google Sign-In and Calendar Access",
    Desc: "Our application uses Google Sign-In to authenticate users securely and to access their Google Calendar. This access is used solely to add events and meeting alerts to the user’s calendar for better scheduling and reminders. We do not store or share your calendar data with third parties, and access is limited to the permissions required for this functionality.",
  },
];

export const userInformation: string[] = [
  "“User Information” for the purpose of this Policy includes the user’s personal information that can be used to uniquely identify or contact a single person including, but not limited to, name, gender, email address, residential address, phone number and other information collected by Techriigour to provide specific services to the user through The Application. The user has the option not to provide specific information if the user wishes not to avail specific service for which this specific information is required. ",
  "If any user is providing any User Information on behalf of any corporation, company, institution, association or other entity, it is assumed that the user has been authorized by such corporation, company, institution, association or other entity to provide such information to Techriigour and the user is solely responsible for the consequences, if any, arising out of providing any such information. ",
  "Techriigour collects information from the user when creating a user account or while posting comments, uploading content or participating in any offers or contests or communicating with the customer support by phone, email or otherwise. ",
  "Techriigour receives, scrutinizes and stores User Information for security and technical reasons such as IP address, login ID, email address, password, devise connection information, transaction history, date, some information automatically collected while user uses The Application, time and duration of the session on The Application. ",
  "Techriigour may occasionally ask the user to complete optional online surveys. The surveys may ask the user for contact information and demographic information such as Zip code, age or income level etc. ",
  "The user can add or update the User Information on a regular basis. When the user updates the User Information, Techriigour will keep a copy of the prior version for its records. ",
];

export const securityanduserrestriction: string[] = [
  "Techriigour implements standard measures to protect against unauthorized access to and unlawful interception of the User Information. However, no application can fully eliminate security risks. Techriigour endeavours to take all measures to protect the security, integrity and confidentiality of the User Information against unauthorized breach and hacking. For the purpose of checking possible vulnerabilities and attacks, Techriigour may conduct periodical internal review of data and security measures on The Application. Techriigour may use such software as it determines is best for maintaining security. However, the internet is not absolutely a secure environment, and The Application cannot ensure or warrant a 100% security of the User Information. ",

  "If any user is provided with any identification code, password or any other piece of information as part of The Application’s security procedure, the user should treat such information as confidential and the user should not disclose it to any third party including to other users. To prevent third party’s access to The Application, it is recommended that the user signs out from the user account after availing the services through The Application. Techriigour has the right to disable the identification code or password, whether chosen by the user or allotted by Techriigour, at any time, if the user fails to comply with instructions or terms, conditions or policies of Techriigour. ",

  "The user is solely responsible for the activities that occur under the user’s account including the confidentiality of the user’s password and Techriigour is not responsible for the same. While using and accessing The Application, the user is responsible for maintaining the confidentiality of the user’s account on any device/equipment through which the user uses and accesses The Application. ",

  "Notwithstanding anything contained in this Policy or elsewhere, Techriigour shall not be held responsible for any loss, damage or misuse of the User Information, if such loss, damage or misuse is attributable to a Force Majeure Event. A “Force Majeure Event” means any event that is beyond the reasonable control of Techriigour and includes, without limitation, fire, flood, explosion, acts of God, civil commotion, strikes, lock outs or industrial action of any kind, riots, insurrection, war, acts of government, power failure, sabotage, computer hacking, unauthorized access to the computer data and storage device, system failure, virus attacks, bugs, device crashes, breach of security and encryption. ",
];

export const generalTerms: string[] = [
  "This Policy is to be read in conjunction with and shall be deemed to be part of The Application’s Terms of Use. ",
  "The User Information resides in Techriigour’ database over Cloud and for a certain period of time even after the user ceases to use or access The Aplication and in such cases Techriigour is not liable for any usage of the User Information after the user ceases to use or access The Application. ",
  "The Users agree and acknowledge that User Information collated through the Application could be stored and processed in any other country across the world. The users acknowledge that for effective provision of The Application’s services in respective territories including territories outside India, the User Information may be stored or processed by trusted third parties. Whenever the User Information is shared with trusted third parties in countries outside India, Techriigour endeavours that the User Information is transferred in accordance with the applicable laws of India. ",
  "The user should be aware that the User Information or other data, the user provides to The Application for availing the services or transacting through The Application could be read, collected, or used by other users or third parties in which case the User Information might be used for sending unsolicited messages or communications for which Techriigour is not responsible.",
];

export const useofinfo: string[] = [
  "Respond to the user’s queries, requests and inquiries ",
  "Update new features of The Application ",
  "Improve and customize The Application services ",
  "Detect and prevent Fraud and abuse of The Application",
  "Examine the identity of the users and the authenticity of offers, delivery or transfer of the offers etc. ",
  "Administer The Application ",
  "Inform any changes in the Terms of Use or this Policy or the Terms and Conditions of specific Brand/s ",
  "Send surveys and marketing communications that Techriigour believes may be of interest to the user ",
  "Help the user address its problems with The Application including addressing any technical problems. ",
  "Protect the integrity of The Application ",
];

export const useofdis: string[] = [
  "Its partner Brand/s for dissemination of Loyalty Points, Special Offers, Campaigns etc.",
  "Third party service providers engaged by Techriigour to perform services on behalf of Techriigour",

  "Third party service providers for the purpose of The Application’s security, maintenance, repair or other technical reasons ",
];
